dataSource:
  url: "jdbc:mysql://localhost:3306/portal"
  driverClassName: 'com.mysql.cj.jdbc.Driver'
  dbCreate: 'update'
  username: 'root'
  password: 'root'

environments:
  development:
    dataSource:
      url: "jdbc:mysql://localhost:3306/portal"
      driverClassName: 'com.mysql.cj.jdbc.Driver'
      dbCreate: 'update'
      username: 'root'
      password: 'root'